"""nutri-105: user_sessions table

Revision ID: 5c56697f0888
Revises: a6609a316935
Create Date: 2026-10-07 10:31:41.778380

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c56697f0888"
down_revision: str | Sequence[str] | None = "a6609a316935"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_sessions_expires", "user_sessions", ["expires_at"], unique=False)
    op.create_index(
        "idx_user_sessions_user_active",
        "user_sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.execute("ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON user_sessions FROM anon")
    op.execute("REVOKE ALL ON user_sessions FROM authenticated")
    op.execute("GRANT ALL ON user_sessions TO service_role")
    op.drop_index(op.f("idx_nutrition_references_category"), table_name="nutrition_references")
    op.drop_index(op.f("idx_nutrition_references_effective"), table_name="nutrition_references")
    op.drop_constraint(op.f("unique_portion_ref"), "portion_references", type_="unique")
    op.drop_index(op.f("idx_profiles_age_group"), table_name="profiles")
    op.drop_index(
        op.f("idx_profiles_deleted_at"),
        table_name="profiles",
        postgresql_where="(deleted_at IS NOT NULL)",
    )
    op.drop_index(op.f("idx_profiles_id"), table_name="profiles")
    op.drop_index(
        op.f("idx_scanned_products_name_search"),
        table_name="scanned_products",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_scanned_products_name_search"),
        "scanned_products",
        [sa.literal_column("to_tsvector('simple'::regconfig, product_name)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_profiles_id"), "profiles", ["id"], unique=False)
    op.create_index(
        op.f("idx_profiles_deleted_at"),
        "profiles",
        ["deleted_at"],
        unique=False,
        postgresql_where="(deleted_at IS NOT NULL)",
    )
    op.create_index(op.f("idx_profiles_age_group"), "profiles", ["age_group"], unique=False)
    op.create_unique_constraint(
        op.f("unique_portion_ref"),
        "portion_references",
        ["name", "measurement_type", "container_type", "container_size"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("idx_nutrition_references_effective"),
        "nutrition_references",
        [sa.literal_column("effective_date DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_nutrition_references_category"),
        "nutrition_references",
        ["category"],
        unique=False,
    )
    op.drop_index(
        "idx_user_sessions_user_active",
        table_name="user_sessions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("idx_user_sessions_expires", table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
